#!/bin/bash
# Power menu using rofi

OPTIONS="󰌾 Lock\n󰍃 Logout\n󰤄 Suspend\n󰜉 Reboot\n󰐥 Shutdown"

CHOICE=$(echo -e "$OPTIONS" | rofi -dmenu -i -p "Power" -theme-str 'window {width: 200px;}')

case "$CHOICE" in
    *Lock) i3lock -c 1e1f22 ;;
    *Logout) i3-msg exit ;;
    *Suspend) systemctl suspend ;;
    *Reboot) systemctl reboot ;;
    *Shutdown) systemctl poweroff ;;
esac
