return {
  {
    "catppuccin/nvim",
    name = "catppuccin",
    priority = 1000,
    opts = {
      flavour = "mocha",
      transparent_background = false,
      term_colors = true,
      color_overrides = {
        mocha = {
          base = "#1e1f22",
          mantle = "#1e1f22",
          crust = "#1e1f22",
          surface0 = "#2b2d30",
          surface1 = "#393b40",
          surface2 = "#4e5157",
          overlay0 = "#6f737a",
          overlay1 = "#8c8c8c",
          overlay2 = "#a8a8a8",
          text = "#bcbec4",
          subtext0 = "#a8a8a8",
          subtext1 = "#bcbec4",
          blue = "#3574f0",
          lavender = "#6c95eb",
          sapphire = "#35a1b0",
          sky = "#35a1b0",
          teal = "#35a1b0",
          green = "#499c54",
          yellow = "#e9b872",
          peach = "#cf8e6d",
          maroon = "#f75464",
          red = "#f75464",
          mauve = "#c77dbb",
          pink = "#c77dbb",
          flamingo = "#c77dbb",
          rosewater = "#c77dbb",
        },
      },
      integrations = {
        cmp = true,
        gitsigns = true,
        nvimtree = true,
        treesitter = true,
        notify = true,
        mini = true,
        native_lsp = {
          enabled = true,
        },
        telescope = true,
        which_key = true,
      },
    },
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "catppuccin",
    },
  },
}
